- name: Create user Administrator
  import_tasks: create_users.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install Docker and docker-compose
  import_tasks: install_docker.yml
  when: ansible_facts['os_family']|lower == 'debian'
