---
####################### Playbook Utilities
# docker_conf -> Tag to install and configure Docker on Debian

####################### Individual hosts
#- hosts: sauron
#- hosts: aragon
#- hosts: aragon-pre
#- hosts: ubuntu-test
####################### Host groups
#- hosts: webservers
- hosts: webservers-pre
#- hosts: webservers-pro
#- hosts: test_servers
  tasks:
  - name: Basic setup for Debian Web Server
    include_role:
      name: base_debian
    tags:	base_debian
